cmd: Controller Class Reference
Controller Class Reference
Class Controller - controller (invoker) in the implementation of the Command pattern.
#include <Controller.h>
Public Member Functions
Controller (unsigned int block_size)
void parse_command (std::unique_ptr< Command > command)
void add_command (std::unique_ptr< Command > command)
Private Member Functions
void worker ()
void output_commands (std::ostream &out)
void execute_commands ()
void clear_commands ()
Static Private Member Functions
static std::string time_to_string (std::time_t *time)
Private Attributes
std::list< std::unique_ptr< Command > > _commands
unsigned int _block_size
unsigned int _command_count
unsigned int _brackets_count
std::string _log_file_name
Detailed Description
Class Controller - controller (invoker) in the implementation of the Command pattern.
Parameters
block_size Command block size.
Definition at line 16 of file Controller.h.
Constructor & Destructor Documentation
Controller()
Controller::Controller (unsigned int block_size) inline explicit
Definition at line 18 of file Controller.h.
                                                 :
        _block_size(block_size), _command_count(0), _brackets_count(0) {}
Member Function Documentation
add_command()
void Controller::add_command (std::unique_ptr< Command > command)
Definition at line 41 of file Controller.cpp.
{
    _commands.emplace_back(std::move(command));
}
Referenced by parse_command().
clear_commands()
void Controller::clear_commands () private
Definition at line 77 of file Controller.cpp.
{
    _commands.clear();
    _command_count = 0;
}
Referenced by worker().
execute_commands()
void Controller::execute_commands () private
Definition at line 71 of file Controller.cpp.
{
    for (const auto& command : _commands) {
        command->execute();
    }
}
Referenced by worker().
output_commands()
void Controller::output_commands (std::ostream & out) private
Definition at line 60 of file Controller.cpp.
{
    out << "bulk: ";
    for (auto it = _commands.cbegin(); it != _commands.cend(); ++it) {
        if (it != _commands.cbegin()) {
            out << ", ";
        }
        out << (*it)->get_text();
    }
    out << std::endl;
}
Referenced by worker().
parse_command()
void Controller::parse_command (std::unique_ptr< Command > command)
Definition at line 8 of file Controller.cpp.
{
    if (_command_count == 0) {
        auto now = std::chrono::system_clock::now();
        std::time_t time = std::chrono::system_clock::to_time_t(now);
        _log_file_name = "bulk" + std::to_string(time) + ".log"; //as specified in the task
        //_log_file_name = "bulk" + time_to_string(&time) + ".log";  //human-readable log file name
    }
    if (command->get_text() == "EOF") {
        if (_brackets_count == 0) {
            worker();
        }
    } else if (command->get_text() == "{") {
        if (_brackets_count == 0) {
            worker();
        }
        ++_brackets_count;
    } else if (command->get_text() == "}") {
        if (_brackets_count > 0) {
            --_brackets_count;
        }
        if (_brackets_count == 0) {
            worker();
        }
    } else {
        add_command(std::move(command));
        ++_command_count;
        if (_command_count == _block_size && _brackets_count == 0) {
            worker();
        }
    }
}
Referenced by main().
time_to_string()
std::string Controller::time_to_string (std::time_t * time) static private
Definition at line 82 of file Controller.cpp.
{
    std::stringstream ss;
    std::tm* tm = localtime(time);
    ss << tm->tm_year + 1900 << "-" << std::setw(2) << std::setfill('0') << tm->tm_mon + 1 << "-"
       << std::setw(2) << std::setfill('0') << tm->tm_mday << "_"
       << std::setw(2) << std::setfill('0') << tm->tm_hour << "-"
       << std::setw(2) << std::setfill('0') << tm->tm_min << "-"
       << std::setw(2) << std::setfill('0') << tm->tm_sec;
    return ss.str();
}
worker()
void Controller::worker () private
Definition at line 45 of file Controller.cpp.
{
    if (_command_count != 0) {
        std::ofstream log_file(_log_file_name);
        if (log_file.is_open()) {
            output_commands(log_file);
            log_file.close();
        } else {
            std::cerr << "Error opening log file!" << std::endl;
        }
        output_commands(std::cout);
        execute_commands();//obviously not need
        clear_commands();
    }
}
Referenced by parse_command().
Member Data Documentation
_block_size
unsigned int Controller::_block_size private
Definition at line 32 of file Controller.h.
Referenced by parse_command().
_brackets_count
unsigned int Controller::_brackets_count private
Definition at line 34 of file Controller.h.
Referenced by parse_command().
_command_count
unsigned int Controller::_command_count private
Definition at line 33 of file Controller.h.
Referenced by clear_commands(), parse_command(), and worker().
_commands
std::list<std::unique_ptr<Command> > Controller::_commands private
Definition at line 31 of file Controller.h.
Referenced by add_command(), clear_commands(), execute_commands(), and output_commands().
_log_file_name
std::string Controller::_log_file_name private
Definition at line 35 of file Controller.h.
Referenced by parse_command(), and worker().
The documentation for this class was generated from the following files:
Controller.h
Controller.cpp